### ISSUE TITLE
1.18.2: "- ANY" is ignored

### ISSUE THREAD

**Issue by synergic777** [SydMontague/SpeedRoads#2]
Hello, on my 1.18.2 Paper server, the `- ANY `is ignored by the SpeedRoads. I hope my description will be understandable enough.

Steps to reproduce;
- Set config containing the  `-ANY`. 
```
# maximum acceleration per tick
stepSize: 0.01
# Affected non-player living entities, may affect performance negatively
# See https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
affectedEntities: []
roads:
  road1:
    speed: 0.5
    blocks:
      - ANY
      - GRAVEL
      - COBBLESTONE
      - COBBLESTONE
```

- Build a road according to the template, but skip the top layer
- road gives a speed effect anyway
- Add the missing top layer with any block
- road is no longer giving the speed effect

Unfortunately, I don't see any error in log files.
